### PR TITLE
Modernize cap_gun source

### PR DESCRIPTION
**Pull request by boosty**
Hi there,

first of all I want to thank you for cap_gun! It's a very useful gem, and I am happy to have it available for the projects I am working on.

However, I felt that the code needed a refactoring, like using bundler, action mailer 3 (to not need a custom TLS hack), travis build and so on.

That's why I created a fork, and released it as a separate gem for now: xing-cap_gun. 
The source is here: https://github.com/xing/cap_gun

Please check the list of commits, maybe you find some changes useful enough to make it into the official version.

Thanks!
Sebastian

### CODE REVIEW

**Comment by colszowka** [comment]
+1 :)

**Comment by rsanheim** [comment]
Hey thanks for the contribution!  

Can you break this up into smaller, more focused pulls?

For example, start with the Travis integration.  Then the action mailer upgrade.  Then any other upgrades or refactoring.  That would be much easier for me to integrate.

**Comment by boosty** [comment]
Hi, and sorry for the late reply.

I tried to create self-contained commits as much as possible. Instead of creating a huge number of pull-requests, maybe you can just cherry-pick the commits you are interested in?

I think it's ok to close this pull-request if you don't want to merge it as a whole.

**Comment by rsanheim** [comment]
Okay, I will close this.

Its just that it is easier to do things if there are several, smaller
focused PR's versus one big one. :).

On Sat, Feb 9, 2013 at 9:04 AM, Sebastian Röbke notifications@github.comwrote:

> Hi, and sorry for the late reply.
> 
> I tried to create self-contained commits as much as possible. Instead of
> creating a huge number of pull-requests, maybe you can just cherry-pick the
> commits you are interested in?
> 
> I think it's ok to close this pull-request if you don't want to merge it
> as a whole.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/relevance/cap_gun/pull/10#issuecomment-13332220..

## 

Engineer @ GitHub
http://github.com/rsanheim

**Pull request closed without merging**
